"""
WOS execution completion helper (issue #669).

Provides maybe_complete_wos_uow — the deferred execution_complete transition
for the async inbox dispatch path.

Background: when the Executor writes a wos_execute message to the inbox (fire-
and-forget), it transitions the UoW to 'executing' rather than 'ready-for-
steward'. The execution_complete audit entry and the final executing →
ready-for-steward transition happen here, only after the subagent confirms
completion by calling write_result.

This module is imported by both inbox_server.py (production) and test code.
It has no dependency on inbox_server's heavy MCP server stack — only on the
orchestration.registry module.

Naming convention: task_id for WOS dispatches is "wos-{uow_id}", set by
route_wos_message in dispatcher_handlers.py.

Close-out protocol: when a UoW with a GitHub issue source transitions to
ready-for-steward, a comment is posted to the source issue summarising the
completion. Source format: "github:issue/N" (set at germination time). Non-GitHub
sources (telegram, system, etc.) are silently skipped — no side effect.
"""

from __future__ import annotations

import logging
import os
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

log = logging.getLogger("wos_completion")

#: Prefix used by route_wos_message to form the task_id for wos_execute dispatches.
WOS_TASK_ID_PREFIX = "wos-"

#: write_result status value that signals successful subagent completion.
WRITE_RESULT_SUCCESS_STATUS = "success"

#: Pattern that identifies a GitHub issue source reference.
#: Format: "github:issue/<number>" (integer issue number, no leading zeros required).
_GITHUB_ISSUE_SOURCE_RE = re.compile(r"^github:issue/(\d+)$")

# ---------------------------------------------------------------------------
# Output classification — pure function
# ---------------------------------------------------------------------------

#: Valid output classification labels (seed/pearl/heat/shit).
_OUTPUT_CLASSIFICATIONS = frozenset({"seed", "pearl", "heat", "shit"})

#: Default classification when no heuristic fires — seed is the conservative
#: choice: assume the output has future value until the Steward evaluates it.
_DEFAULT_CLASSIFICATION = "seed"


def classify_uow_output(output_ref: str | None, result_text: str | None) -> str:
    """
    Heuristic classification of a UoW's output type.

    Pure function — no side effects, no I/O. Callers supply the output_ref path
    and (optionally) the write_result text so the classifier can inspect both
    without touching the filesystem or the registry.

    Classification table (first match wins):
    - "pearl"   : output_ref ends with .md or .txt AND result text mentions "PR #"
                  (UoW produced a PR — a concrete deliverable)
    - "pearl"   : result text contains "pull request" or "PR #" or "merged"
    - "heat"    : result text contains "nothing to do" or "no changes" or "skipped"
    - "seed"    : default — output has future value but no stronger signal present

    "shit" is not generated by the classifier — it requires human judgment and is
    set by the Steward during evaluation.

    Args:
        output_ref: The output_ref path written to the UoW at claim time. May be None.
        result_text: The text field from the write_result call. May be None or empty.

    Returns:
        One of "pearl", "heat", or "seed" (default).
    """
    normalized = (result_text or "").lower()

    # Pearl: produced a pull request
    if re.search(r"\bpr\s*#\d+\b|pull request|merged", normalized):
        return "pearl"

    # Heat: found nothing to do
    if re.search(r"\bnothing to do\b|\bno changes\b|\bskipped\b|\bno-op\b", normalized):
        return "heat"

    # Default: conservative — assume future value
    return _DEFAULT_CLASSIFICATION


# ---------------------------------------------------------------------------
# Close-out comment — pure builder + side-effecting poster
# ---------------------------------------------------------------------------

def _build_closeout_comment(
    uow_id: str,
    output_classification: str,
    result_text: str | None,
    agent_type: str,
    date_str: str,
) -> str:
    """
    Pure builder for the GitHub close-out comment body.

    Builds the structured comment that is posted to the source issue when a UoW
    completes. All inputs are plain strings — no I/O, no registry access.

    Args:
        uow_id: The WOS unit-of-work ID.
        output_classification: One of seed/pearl/heat/shit.
        result_text: One-sentence summary from the subagent's write_result call.
                     Truncated to 200 chars to keep the comment readable.
        agent_type: The executor type that ran the UoW (e.g. "functional-engineer").
        date_str: ISO date string (YYYY-MM-DD) for the completion date.

    Returns:
        Formatted markdown comment body string.
    """
    summary_raw = (result_text or "").strip()
    # Truncate to first sentence or 200 chars, whichever is shorter
    first_sentence_end = summary_raw.find(". ")
    if 0 < first_sentence_end < 200:
        summary = summary_raw[: first_sentence_end + 1]
    else:
        summary = summary_raw[:200] + ("…" if len(summary_raw) > 200 else "")

    return (
        f"## WOS UoW Complete — {uow_id}\n"
        f"**Output type:** {output_classification}\n"
        f"**Summary:** {summary}\n"
        f"**Executed by:** {agent_type} on {date_str}\n"
        f"**Result:** {uow_id}.result.json\n"
    )


def _post_github_comment(
    repo: str,
    issue_number: int,
    comment_body: str,
    gh_bin: str = "gh",
) -> None:
    """
    Post a comment to a GitHub issue via the gh CLI.

    Side-effecting: spawns a subprocess. Non-blocking on failure — logs a warning
    and returns so that the UoW transition is never gated on comment delivery.

    Args:
        repo: GitHub repo slug in "owner/repo" format.
        issue_number: Integer issue number.
        comment_body: Markdown comment body to post.
        gh_bin: Path to the gh binary (injectable for tests).
    """
    try:
        subprocess.run(
            [gh_bin, "issue", "comment", str(issue_number), "--repo", repo, "--body", comment_body],
            capture_output=True,
            timeout=30,
            check=True,
        )
        log.info(
            "wos_completion: posted close-out comment to %s#%d",
            repo,
            issue_number,
        )
    except subprocess.CalledProcessError as exc:
        log.warning(
            "wos_completion: gh issue comment failed for %s#%d — exit %d: %s",
            repo,
            issue_number,
            exc.returncode,
            (exc.stderr or b"").decode(errors="replace")[:300],
        )
    except Exception as exc:
        log.warning(
            "wos_completion: could not post close-out comment to %s#%d — %s: %s",
            repo,
            issue_number,
            type(exc).__name__,
            exc,
        )


def _extract_github_issue(source: str) -> tuple[str, int] | None:
    """
    Parse a UoW source string and return (repo, issue_number) for GitHub sources.

    Pure function — no side effects.

    Args:
        source: The UoW source field. Expected format: "github:issue/N".
                The repo slug is read from the LOBSTER_WOS_REPO env var (default:
                "dcetlin/Lobster") so that the source field can remain source-agnostic.

    Returns:
        (repo, issue_number) tuple when source is a GitHub issue reference, else None.
    """
    m = _GITHUB_ISSUE_SOURCE_RE.match(source or "")
    if not m:
        return None
    issue_number = int(m.group(1))
    repo = os.environ.get("LOBSTER_WOS_REPO", "dcetlin/Lobster")
    return (repo, issue_number)


def _post_closeout_comment_if_github(
    uow_id: str,
    source: str,
    output_ref: str | None,
    result_text: str | None,
    agent_type: str,
    gh_bin: str = "gh",
) -> None:
    """
    Classify the UoW output and post a close-out comment to the source GitHub issue.

    No-op when the source is not a GitHub issue reference. Side effects
    (subprocess call) are isolated here — callers remain pure with respect to
    the registry transition.

    Args:
        uow_id: The WOS unit-of-work ID.
        source: The UoW source field (e.g. "github:issue/123" or "telegram").
        output_ref: The output_ref path (used as fallback for classification).
        result_text: Text from the subagent's write_result call.
        agent_type: The executor_type string from the UoW workflow_artifact.
        gh_bin: Path to the gh binary (injectable for tests).
    """
    parsed = _extract_github_issue(source)
    if parsed is None:
        log.debug(
            "wos_completion: source %r is not a GitHub issue — skipping close-out comment",
            source,
        )
        return

    repo, issue_number = parsed
    classification = classify_uow_output(output_ref, result_text)
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    comment_body = _build_closeout_comment(
        uow_id=uow_id,
        output_classification=classification,
        result_text=result_text,
        agent_type=agent_type,
        date_str=date_str,
    )
    _post_github_comment(repo, issue_number, comment_body, gh_bin=gh_bin)


# ---------------------------------------------------------------------------
# Main entry point — called by inbox_server.py on every write_result
# ---------------------------------------------------------------------------

def maybe_complete_wos_uow(
    task_id: str,
    status: str,
    result_text: str | None = None,
    gh_bin: str = "gh",
) -> None:
    """
    Transition a WOS UoW from 'executing' to 'ready-for-steward' when its
    subagent calls write_result with status='success'.

    This is the deferred execution_complete transition for the async inbox
    dispatch path (issue #669). The Executor transitions active → executing at
    dispatch time; this function fires the execution_complete audit entry and
    the executing → ready-for-steward transition only after the subagent
    confirms completion via write_result.

    After a successful transition, if the UoW source is a GitHub issue, a
    structured close-out comment is posted to that issue. Non-GitHub sources
    are skipped silently. Comment failure never blocks the registry transition.

    Conditions required to fire:
    - task_id starts with WOS_TASK_ID_PREFIX ("wos-")
    - status == "success" (only successful completions advance the UoW)
    - UoW exists in the registry with status == "executing"

    A UoW not in 'executing' status is skipped silently — this handles the
    case where TTL recovery already failed the UoW, or where a duplicate
    write_result arrives after the first has already completed it.

    Errors are logged but never raised — write_result delivery must not be
    blocked by registry update failures.

    Args:
        task_id: The task_id string from the write_result call.
                 Expected format: "wos-{uow_id}".
        status:  The status from the write_result call ("success" or "error").
        result_text: Optional text from the write_result call; used in the
                     close-out comment summary and output classification.
        gh_bin:  Path to the gh CLI binary (injectable for tests; default "gh").
    """
    if not task_id.startswith(WOS_TASK_ID_PREFIX):
        return
    if status != WRITE_RESULT_SUCCESS_STATUS:
        # Only advance to ready-for-steward on success. Failed write_results
        # leave the UoW in 'executing' for TTL recovery to handle.
        return

    uow_id = task_id[len(WOS_TASK_ID_PREFIX):]
    try:
        from orchestration.registry import Registry, UoWStatus

        workspace = Path(os.environ.get("LOBSTER_WORKSPACE", Path.home() / "lobster-workspace"))
        env_override = os.environ.get("REGISTRY_DB_PATH")
        db_path = Path(env_override) if env_override else workspace / "orchestration" / "registry.db"

        if not db_path.exists():
            log.debug(
                "maybe_complete_wos_uow: registry DB not found at %s — "
                "skipping (no WOS install or test env)",
                db_path,
            )
            return

        registry = Registry(db_path)
        uow = registry.get(uow_id)
        if uow is None:
            log.debug(
                "maybe_complete_wos_uow: UoW %r not found in registry — skipping",
                uow_id,
            )
            return

        if uow.status != UoWStatus.EXECUTING:
            log.debug(
                "maybe_complete_wos_uow: UoW %r is in status %r (expected 'executing') — "
                "skipping (already recovered or duplicate write_result)",
                uow_id,
                uow.status,
            )
            return

        output_ref = uow.output_ref or ""
        registry.complete_uow(uow_id, output_ref)
        log.info(
            "maybe_complete_wos_uow: UoW %r transitioned executing → ready-for-steward "
            "(execution_complete written on write_result confirmation)",
            uow_id,
        )

        # Close-out protocol: post a structured comment to the source GitHub issue.
        # Non-GitHub sources are silently skipped. Comment failure is non-fatal.
        uow_source = uow.source or ""
        agent_type = "functional-engineer"  # conservative default; UoW register is available below
        # Use uow.register to pick a more descriptive agent_type label when available.
        if hasattr(uow, "register") and uow.register:
            agent_type = uow.register

        _post_closeout_comment_if_github(
            uow_id=uow_id,
            source=uow_source,
            output_ref=output_ref,
            result_text=result_text,
            agent_type=agent_type,
            gh_bin=gh_bin,
        )

    except Exception as exc:
        log.warning(
            "maybe_complete_wos_uow: failed to complete UoW %r — %s: %s",
            uow_id,
            type(exc).__name__,
            exc,
        )
