"""
Tests for the Obsidian <-> DB bidirectional sync script.

Tests derive from spec requirements:
- parse_active_todos() correctly identifies done/new/moved items
- dedup_key generation is consistent with existing items in src.los.db
- sync_obsidian_to_db() is idempotent — running twice produces the same result
- Priority is updated when an item moves to a different section
- Items already done in DB are not re-opened by sync

No file system writes occur in unit tests — all vault and DB operations use
in-memory or tmp-path fixtures.
"""
from __future__ import annotations

import sqlite3
import sys
import textwrap
from pathlib import Path
from unittest.mock import patch

import pytest

# Add scheduled-tasks to path so we can import the script directly
# (same pattern as test_granola_state.py)
_REPO_ROOT = Path(__file__).parent.parent.parent.parent
_TASKS_DIR = _REPO_ROOT / "scheduled-tasks"
if str(_TASKS_DIR) not in sys.path:
    sys.path.insert(0, str(_TASKS_DIR))
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from src.los.db import (
    compute_dedup_key,
    connect,
    insert_action_item,
    mark_done,
    get_item_by_id,
    ActionItemStatus,
)
from todo_obsidian_sync import (  # noqa: E402
    ParsedTodos,
    ParsedItem,
    PRIORITY_URGENT_MAX,
    PRIORITY_ACTIVE_MAX,
    OBSIDIAN_SOURCE,
    parse_active_todos,
    sync_obsidian_to_db,
    render_active_todos,
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def conn(tmp_path: Path) -> sqlite3.Connection:
    db = connect(tmp_path / "test.db")
    yield db
    db.close()


SAMPLE_ACTIVE_TODOS = textwrap.dedent("""\
    # ✅ ACTIVE TODOS
    *Generated by LOS — 5 open items as of 2026-05-10*

    ## Urgent / This Week (P1–P3)
    - [ ] Book flight Boston to Miami  *(relationships)*
    - [x] Call the dentist  *(health)*

    ## Active (P4–P6)

    ### work-angellist
    - [ ] Complete FC work items  *(work-angellist)*

    ### lobster
    - [x] Connect Obsidian to Lobster  *(lobster)*
    - [ ] Time box Lobster stuff  *(lobster)*

    ## Someday / Aspirational (P7–P9)
    - [ ] Learn Rust  *(learning)*

    ---
    *To mark done, dismiss, or snooze: tell Lobster via Telegram, or check the box in Obsidian.*
""")


# ---------------------------------------------------------------------------
# dedup_key consistency
# ---------------------------------------------------------------------------


def test_dedup_key_matches_db_implementation() -> None:
    """dedup_key in sync must use the same algorithm as src.los.db.compute_dedup_key."""
    # The sync script imports compute_dedup_key directly from src.los.db.
    # This test verifies the expected normalization — lowercase, strip punctuation, collapse whitespace.
    key = compute_dedup_key("Call the dentist!")
    assert key == compute_dedup_key("CALL THE DENTIST")
    assert len(key) == 16
    assert key == compute_dedup_key("call   the  dentist")


def test_dedup_key_is_deterministic() -> None:
    """Same text always produces the same key."""
    text = "Complete FC work items"
    assert compute_dedup_key(text) == compute_dedup_key(text)


def test_dedup_key_differs_for_different_text() -> None:
    """Different texts produce different keys."""
    assert compute_dedup_key("Book flight") != compute_dedup_key("Learn Rust")


# ---------------------------------------------------------------------------
# parse_active_todos — structure
# ---------------------------------------------------------------------------


def test_parse_active_todos_returns_parsed_todos() -> None:
    """parse_active_todos must return a ParsedTodos with open and done lists."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    assert isinstance(result, ParsedTodos)


def test_parse_identifies_done_items() -> None:
    """Items marked [x] must appear in ParsedTodos.done."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    done_texts = [item.text for item in result.done]
    assert "Call the dentist" in done_texts
    assert "Connect Obsidian to Lobster" in done_texts


def test_parse_identifies_open_items() -> None:
    """Items marked [ ] must appear in ParsedTodos.open."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    open_texts = [item.text for item in result.open]
    assert "Book flight Boston to Miami" in open_texts
    assert "Complete FC work items" in open_texts
    assert "Time box Lobster stuff" in open_texts
    assert "Learn Rust" in open_texts


def test_parse_done_items_not_in_open() -> None:
    """Items marked [x] must not appear in the open list."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    open_texts = {item.text for item in result.open}
    assert "Call the dentist" not in open_texts
    assert "Connect Obsidian to Lobster" not in open_texts


# ---------------------------------------------------------------------------
# parse_active_todos — priority assignment
# ---------------------------------------------------------------------------


def test_parse_assigns_urgent_priority_to_p1_p3_items() -> None:
    """Items under 'Urgent / This Week' header must get priority <= PRIORITY_URGENT_MAX."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    urgent_items = [item for item in result.open if item.text == "Book flight Boston to Miami"]
    assert len(urgent_items) == 1
    assert urgent_items[0].priority <= PRIORITY_URGENT_MAX


def test_parse_assigns_active_priority_to_p4_p6_items() -> None:
    """Items under 'Active' header must get priority in active range."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    active_items = [item for item in result.open if item.text == "Complete FC work items"]
    assert len(active_items) == 1
    assert PRIORITY_URGENT_MAX < active_items[0].priority <= PRIORITY_ACTIVE_MAX


def test_parse_assigns_someday_priority_to_p7_p9_items() -> None:
    """Items under 'Someday / Aspirational' header must get priority > PRIORITY_ACTIVE_MAX."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    someday_items = [item for item in result.open if item.text == "Learn Rust"]
    assert len(someday_items) == 1
    assert someday_items[0].priority > PRIORITY_ACTIVE_MAX


def test_parse_extracts_workstream_from_section_header() -> None:
    """Items under workstream subsections must have workstream set."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    lobster_items = [item for item in result.open if item.text == "Time box Lobster stuff"]
    assert len(lobster_items) == 1
    assert lobster_items[0].workstream == "lobster"


def test_parse_items_have_dedup_key() -> None:
    """Every parsed item must have a non-empty dedup_key."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    for item in result.open + result.done:
        assert item.dedup_key, f"Item missing dedup_key: {item.text!r}"
        assert len(item.dedup_key) == 16


def test_parse_dedup_key_consistent_with_db() -> None:
    """Parsed items' dedup_key must match what compute_dedup_key returns for their text."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    for item in result.open + result.done:
        expected = compute_dedup_key(item.text)
        assert item.dedup_key == expected, (
            f"dedup_key mismatch for {item.text!r}: got {item.dedup_key!r}, expected {expected!r}"
        )


# ---------------------------------------------------------------------------
# sync_obsidian_to_db — done marking
# ---------------------------------------------------------------------------


def test_sync_marks_done_items_in_db(conn: sqlite3.Connection) -> None:
    """Items marked [x] in file but open in DB must be set to status='done'.

    Only items already in DB are affected — done_count only counts transitions
    from open→done, not [x] items that didn't exist in DB.
    """
    # Insert "Call the dentist" as open — it appears [x] in the file
    row_id = insert_action_item(conn, text="Call the dentist", source="telegram", source_message_id=None)

    result = sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)

    item = get_item_by_id(conn, row_id)
    assert item.status == ActionItemStatus.DONE
    assert item.done_at is not None
    # Only 1 done transition: "Call the dentist" was open in DB; "Connect Obsidian to Lobster"
    # was not in DB at all so no transition counted
    assert result.done_count == 1


def test_sync_sets_done_at_timestamp(conn: sqlite3.Connection) -> None:
    """mark_done must set done_at to a non-empty ISO timestamp."""
    row_id = insert_action_item(conn, text="Call the dentist", source="telegram", source_message_id=None)
    sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)
    item = get_item_by_id(conn, row_id)
    assert item.done_at is not None
    assert "T" in item.done_at  # ISO-8601 format


def test_sync_does_not_reopen_already_done_items(conn: sqlite3.Connection) -> None:
    """An item already done in DB that appears open in file must NOT be reopened."""
    row_id = insert_action_item(conn, text="Book flight Boston to Miami", source="telegram", source_message_id=None)
    mark_done(conn, row_id)

    # "Book flight Boston to Miami" is [ ] (open) in the file
    sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)

    item = get_item_by_id(conn, row_id)
    # Must remain done — the file says open but DB has authoritative done status
    assert item.status == ActionItemStatus.DONE


# ---------------------------------------------------------------------------
# sync_obsidian_to_db — new item insertion
# ---------------------------------------------------------------------------


def test_sync_inserts_new_items_not_in_db(conn: sqlite3.Connection) -> None:
    """Open items in file with no matching dedup_key in DB must be inserted."""
    result = sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)

    # All 4 open items ("Book flight", "Complete FC", "Time box Lobster", "Learn Rust")
    # are not in the empty DB, so they should be inserted
    assert result.inserted_count == 4


def test_sync_inserted_items_have_obsidian_source(conn: sqlite3.Connection) -> None:
    """Items inserted from ACTIVE TODOS.md must have source=OBSIDIAN_SOURCE."""
    sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)
    cur = conn.execute("SELECT source FROM action_items WHERE source = ?", (OBSIDIAN_SOURCE,))
    rows = cur.fetchall()
    assert len(rows) == 4


def test_sync_does_not_duplicate_existing_open_items(conn: sqlite3.Connection) -> None:
    """Items already open in DB must not be inserted again."""
    row_id = insert_action_item(
        conn, text="Book flight Boston to Miami", source="telegram", source_message_id=None
    )

    result = sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)

    # Should only insert the 3 remaining new items (not the one already present)
    assert result.inserted_count == 3

    # Verify the original row was not duplicated
    cur = conn.execute(
        "SELECT COUNT(*) FROM action_items WHERE dedup_key = ?",
        (compute_dedup_key("Book flight Boston to Miami"),),
    )
    count = cur.fetchone()[0]
    assert count == 1


# ---------------------------------------------------------------------------
# sync_obsidian_to_db — priority update
# ---------------------------------------------------------------------------


def test_sync_updates_priority_when_item_moves_sections(conn: sqlite3.Connection) -> None:
    """If an item exists in DB with different priority than its file section, update priority."""
    # Insert "Book flight Boston to Miami" as low priority (7) but it's in Urgent section (P1-P3)
    row_id = insert_action_item(
        conn, text="Book flight Boston to Miami", source="telegram", source_message_id=None, priority=7
    )
    item_before = get_item_by_id(conn, row_id)
    assert item_before.priority == 7

    sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)

    item_after = get_item_by_id(conn, row_id)
    assert item_after.priority <= PRIORITY_URGENT_MAX, (
        f"Priority should have been updated to urgent range, got {item_after.priority}"
    )
    # Verify priority actually changed
    assert item_after.priority != 7


def test_sync_does_not_change_priority_when_item_already_in_same_band(conn: sqlite3.Connection) -> None:
    """If an item is already in the same priority band as its file section, leave it alone."""
    # Insert "Learn Rust" with priority 8 (someday band = P7–P9)
    row_id = insert_action_item(
        conn, text="Learn Rust", source="telegram", source_message_id=None, priority=8
    )

    sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)

    item_after = get_item_by_id(conn, row_id)
    assert item_after.priority == 8


# ---------------------------------------------------------------------------
# sync_obsidian_to_db — idempotency
# ---------------------------------------------------------------------------


def test_sync_is_idempotent(conn: sqlite3.Connection) -> None:
    """Running sync twice must produce the same DB state as running it once."""
    result1 = sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)
    result2 = sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)

    # No new inserts on second run — all items already in DB
    assert result2.inserted_count == 0

    # Total row count must be the same after both runs
    cur = conn.execute("SELECT COUNT(*) FROM action_items")
    count = cur.fetchone()[0]
    assert count == result1.inserted_count + result1.done_count


def test_sync_idempotent_done_status(conn: sqlite3.Connection) -> None:
    """Running sync twice does not create duplicate done transitions."""
    row_id = insert_action_item(conn, text="Call the dentist", source="telegram", source_message_id=None)

    sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)
    first_done_at = get_item_by_id(conn, row_id).done_at

    sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)
    second_done_at = get_item_by_id(conn, row_id).done_at

    # done_at should not be overwritten on second pass (item is already done)
    assert first_done_at == second_done_at


# ---------------------------------------------------------------------------
# sync_obsidian_to_db — SyncResult summary
# ---------------------------------------------------------------------------


def test_sync_result_summary_counts_are_accurate(conn: sqlite3.Connection) -> None:
    """SyncResult must accurately report done/inserted/priority_changed counts."""
    # Pre-insert one item at wrong priority so priority_changed fires
    # "Book flight Boston to Miami" is in Urgent section (P1-P3), inserting at priority=8
    row_id = insert_action_item(
        conn, text="Book flight Boston to Miami", source="telegram", source_message_id=None, priority=8
    )
    # Pre-insert "Call the dentist" as open — it appears [x] in file, so should be marked done
    row_dentist = insert_action_item(conn, text="Call the dentist", source="telegram", source_message_id=None)

    result = sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)

    # "Call the dentist" was open → should be marked done (1 transition)
    assert result.done_count == 1
    assert get_item_by_id(conn, row_dentist).status == ActionItemStatus.DONE
    # "Complete FC work items", "Time box Lobster stuff", "Learn Rust" are new open items not in DB
    assert result.inserted_count == 3
    # "Book flight" was at wrong priority band (8 vs urgent max 3)
    assert result.priority_changed_count == 1


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------


def test_parse_handles_empty_file() -> None:
    """parse_active_todos on an empty string must return empty lists, not raise."""
    result = parse_active_todos("")
    assert result.open == []
    assert result.done == []


def test_parse_handles_file_with_no_checkboxes() -> None:
    """parse_active_todos on a file with no checkbox lines returns empty lists."""
    content = "# Some file\n\nNo checkboxes here.\n"
    result = parse_active_todos(content)
    assert result.open == []
    assert result.done == []


def test_parse_strips_inline_workstream_annotation() -> None:
    """Item text must not include the trailing *(workstream)* annotation."""
    content = "## Active (P4–P6)\n\n### lobster\n- [ ] Connect Obsidian to Lobster  *(lobster)*\n"
    result = parse_active_todos(content)
    assert len(result.open) == 1
    assert result.open[0].text == "Connect Obsidian to Lobster"
    assert "*(lobster)*" not in result.open[0].text


def test_sync_handles_empty_db_gracefully(conn: sqlite3.Connection) -> None:
    """sync_obsidian_to_db with an empty DB must not raise."""
    result = sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)
    assert result is not None


# ---------------------------------------------------------------------------
# render_active_todos — format verification
# ---------------------------------------------------------------------------


def test_render_produces_urgent_section(conn: sqlite3.Connection) -> None:
    """render_active_todos must include the 'Urgent / This Week' section header."""
    insert_action_item(conn, text="Urgent task", source="telegram", source_message_id=None, priority=2)
    output = render_active_todos(conn)
    assert "Urgent / This Week" in output


def test_render_produces_someday_section(conn: sqlite3.Connection) -> None:
    """render_active_todos must include the 'Someday / Aspirational' section header."""
    insert_action_item(conn, text="Someday task", source="telegram", source_message_id=None, priority=8)
    output = render_active_todos(conn)
    assert "Someday / Aspirational" in output


def test_render_includes_open_items_as_checkboxes(conn: sqlite3.Connection) -> None:
    """render_active_todos must render open items as '- [ ] ...' checkboxes."""
    insert_action_item(conn, text="Buy milk", source="telegram", source_message_id=None)
    output = render_active_todos(conn)
    assert "- [ ] Buy milk" in output


def test_render_excludes_done_items(conn: sqlite3.Connection) -> None:
    """render_active_todos must not include items with status='done'."""
    row_id = insert_action_item(conn, text="Done task", source="telegram", source_message_id=None)
    mark_done(conn, row_id)
    output = render_active_todos(conn)
    assert "Done task" not in output


def test_render_has_generation_header(conn: sqlite3.Connection) -> None:
    """render_active_todos must include the '# ✅ ACTIVE TODOS' title."""
    output = render_active_todos(conn)
    assert "# ✅ ACTIVE TODOS" in output
