"""
Tests for the Obsidian <-> DB bidirectional sync script.

Tests derive from spec requirements:
- parse_active_todos() correctly identifies done/new/moved items
- dedup_key generation is consistent with existing items in src.los.db
- sync_obsidian_to_db() is idempotent — running twice produces the same result
- Priority is updated when an item moves to a different section
- Items already done in DB are not re-opened by sync
- Attribution sub-bullets are rendered for all four source types

No file system writes occur in unit tests — all vault and DB operations use
in-memory or tmp-path fixtures.
"""
from __future__ import annotations

import sqlite3
import sys
import textwrap
from pathlib import Path
from unittest.mock import patch

import pytest

# Add scheduled-tasks to path so we can import the script directly
# (same pattern as test_granola_state.py)
_REPO_ROOT = Path(__file__).parent.parent.parent.parent
_TASKS_DIR = _REPO_ROOT / "scheduled-tasks"
if str(_TASKS_DIR) not in sys.path:
    sys.path.insert(0, str(_TASKS_DIR))
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from src.los.db import (
    compute_dedup_key,
    connect,
    insert_action_item,
    mark_done,
    mark_snoozed,
    get_item_by_id,
    ActionItemStatus,
)
from obsidian_sync_core import (  # noqa: E402
    format_attribution,
    _render_attribution_line,
    ATTRIBUTION_LINE_RE,
    apply_status_delta,
    _LOBSTER_ADDITIONS_MARKER,
    _LOBSTER_ADDITIONS_END,
)
from todo_obsidian_sync import (  # noqa: E402
    ParsedTodos,
    ParsedItem,
    PRIORITY_URGENT_MAX,
    PRIORITY_ACTIVE_MAX,
    OBSIDIAN_SOURCE,
    parse_active_todos,
    sync_obsidian_to_db,
    render_active_todos,
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def conn(tmp_path: Path) -> sqlite3.Connection:
    db = connect(tmp_path / "test.db")
    yield db
    db.close()


SAMPLE_ACTIVE_TODOS = textwrap.dedent("""\
    # ✅ ACTIVE TODOS
    *Generated by LOS — 5 open items as of 2026-05-10*

    ## Urgent / This Week (P1–P3)
    - [ ] Book flight Boston to Miami  *(relationships)*
    - [x] Call the dentist  *(health)*

    ## Active (P4–P6)

    ### work-angellist
    - [ ] Complete FC work items  *(work-angellist)*

    ### lobster
    - [x] Connect Obsidian to Lobster  *(lobster)*
    - [ ] Time box Lobster stuff  *(lobster)*

    ## Someday / Aspirational (P7–P9)
    - [ ] Learn Rust  *(learning)*

    ---
    *To mark done, dismiss, or snooze: tell Lobster via Telegram, or check the box in Obsidian.*
""")


# ---------------------------------------------------------------------------
# dedup_key consistency
# ---------------------------------------------------------------------------


def test_dedup_key_matches_db_implementation() -> None:
    """dedup_key in sync must use the same algorithm as src.los.db.compute_dedup_key."""
    # The sync script imports compute_dedup_key directly from src.los.db.
    # This test verifies the expected normalization — lowercase, strip punctuation, collapse whitespace.
    key = compute_dedup_key("Call the dentist!")
    assert key == compute_dedup_key("CALL THE DENTIST")
    assert len(key) == 16
    assert key == compute_dedup_key("call   the  dentist")


def test_dedup_key_is_deterministic() -> None:
    """Same text always produces the same key."""
    text = "Complete FC work items"
    assert compute_dedup_key(text) == compute_dedup_key(text)


def test_dedup_key_differs_for_different_text() -> None:
    """Different texts produce different keys."""
    assert compute_dedup_key("Book flight") != compute_dedup_key("Learn Rust")


# ---------------------------------------------------------------------------
# parse_active_todos — structure
# ---------------------------------------------------------------------------


def test_parse_active_todos_returns_parsed_todos() -> None:
    """parse_active_todos must return a ParsedTodos with open and done lists."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    assert isinstance(result, ParsedTodos)


def test_parse_identifies_done_items() -> None:
    """Items marked [x] must appear in ParsedTodos.done."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    done_texts = [item.text for item in result.done]
    assert "Call the dentist" in done_texts
    assert "Connect Obsidian to Lobster" in done_texts


def test_parse_identifies_open_items() -> None:
    """Items marked [ ] must appear in ParsedTodos.open."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    open_texts = [item.text for item in result.open]
    assert "Book flight Boston to Miami" in open_texts
    assert "Complete FC work items" in open_texts
    assert "Time box Lobster stuff" in open_texts
    assert "Learn Rust" in open_texts


def test_parse_done_items_not_in_open() -> None:
    """Items marked [x] must not appear in the open list."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    open_texts = {item.text for item in result.open}
    assert "Call the dentist" not in open_texts
    assert "Connect Obsidian to Lobster" not in open_texts


# ---------------------------------------------------------------------------
# parse_active_todos — priority assignment
# ---------------------------------------------------------------------------


def test_parse_assigns_urgent_priority_to_p1_p3_items() -> None:
    """Items under 'Urgent / This Week' header must get priority <= PRIORITY_URGENT_MAX."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    urgent_items = [item for item in result.open if item.text == "Book flight Boston to Miami"]
    assert len(urgent_items) == 1
    assert urgent_items[0].priority <= PRIORITY_URGENT_MAX


def test_parse_assigns_active_priority_to_p4_p6_items() -> None:
    """Items under 'Active' header must get priority in active range."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    active_items = [item for item in result.open if item.text == "Complete FC work items"]
    assert len(active_items) == 1
    assert PRIORITY_URGENT_MAX < active_items[0].priority <= PRIORITY_ACTIVE_MAX


def test_parse_assigns_someday_priority_to_p7_p9_items() -> None:
    """Items under 'Someday / Aspirational' header must get priority > PRIORITY_ACTIVE_MAX."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    someday_items = [item for item in result.open if item.text == "Learn Rust"]
    assert len(someday_items) == 1
    assert someday_items[0].priority > PRIORITY_ACTIVE_MAX


def test_parse_extracts_workstream_from_section_header() -> None:
    """Items under workstream subsections must have workstream set."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    lobster_items = [item for item in result.open if item.text == "Time box Lobster stuff"]
    assert len(lobster_items) == 1
    assert lobster_items[0].workstream == "lobster"


def test_parse_items_have_dedup_key() -> None:
    """Every parsed item must have a non-empty dedup_key."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    for item in result.open + result.done:
        assert item.dedup_key, f"Item missing dedup_key: {item.text!r}"
        assert len(item.dedup_key) == 16


def test_parse_dedup_key_consistent_with_db() -> None:
    """Parsed items' dedup_key must match what compute_dedup_key returns for their text."""
    result = parse_active_todos(SAMPLE_ACTIVE_TODOS)
    for item in result.open + result.done:
        expected = compute_dedup_key(item.text)
        assert item.dedup_key == expected, (
            f"dedup_key mismatch for {item.text!r}: got {item.dedup_key!r}, expected {expected!r}"
        )


# ---------------------------------------------------------------------------
# sync_obsidian_to_db — done marking
# ---------------------------------------------------------------------------


def test_sync_marks_done_items_in_db(conn: sqlite3.Connection) -> None:
    """Items marked [x] in file but open in DB must be set to status='done'.

    Only items already in DB are affected — done_count only counts transitions
    from open→done, not [x] items that didn't exist in DB.
    """
    # Insert "Call the dentist" as open — it appears [x] in the file
    row_id = insert_action_item(conn, text="Call the dentist", source="telegram", source_message_id=None)

    result = sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)

    item = get_item_by_id(conn, row_id)
    assert item.status == ActionItemStatus.DONE
    assert item.done_at is not None
    # Only 1 done transition: "Call the dentist" was open in DB; "Connect Obsidian to Lobster"
    # was not in DB at all so no transition counted
    assert result.done_count == 1


def test_sync_sets_done_at_timestamp(conn: sqlite3.Connection) -> None:
    """mark_done must set done_at to a non-empty ISO timestamp."""
    row_id = insert_action_item(conn, text="Call the dentist", source="telegram", source_message_id=None)
    sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)
    item = get_item_by_id(conn, row_id)
    assert item.done_at is not None
    assert "T" in item.done_at  # ISO-8601 format


def test_sync_does_not_reopen_already_done_items(conn: sqlite3.Connection) -> None:
    """An item already done in DB that appears open in file must NOT be reopened."""
    row_id = insert_action_item(conn, text="Book flight Boston to Miami", source="telegram", source_message_id=None)
    mark_done(conn, row_id)

    # "Book flight Boston to Miami" is [ ] (open) in the file
    sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)

    item = get_item_by_id(conn, row_id)
    # Must remain done — the file says open but DB has authoritative done status
    assert item.status == ActionItemStatus.DONE


# ---------------------------------------------------------------------------
# sync_obsidian_to_db — new item insertion
# ---------------------------------------------------------------------------


def test_sync_inserts_new_items_not_in_db(conn: sqlite3.Connection) -> None:
    """Open items in file with no matching dedup_key in DB must be inserted."""
    result = sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)

    # All 4 open items ("Book flight", "Complete FC", "Time box Lobster", "Learn Rust")
    # are not in the empty DB, so they should be inserted
    assert result.inserted_count == 4


def test_sync_inserted_items_have_obsidian_source(conn: sqlite3.Connection) -> None:
    """Items inserted from ACTIVE TODOS.md must have source=OBSIDIAN_SOURCE."""
    sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)
    cur = conn.execute("SELECT source FROM action_items WHERE source = ?", (OBSIDIAN_SOURCE,))
    rows = cur.fetchall()
    assert len(rows) == 4


def test_sync_does_not_duplicate_existing_open_items(conn: sqlite3.Connection) -> None:
    """Items already open in DB must not be inserted again."""
    row_id = insert_action_item(
        conn, text="Book flight Boston to Miami", source="telegram", source_message_id=None
    )

    result = sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)

    # Should only insert the 3 remaining new items (not the one already present)
    assert result.inserted_count == 3

    # Verify the original row was not duplicated
    cur = conn.execute(
        "SELECT COUNT(*) FROM action_items WHERE dedup_key = ?",
        (compute_dedup_key("Book flight Boston to Miami"),),
    )
    count = cur.fetchone()[0]
    assert count == 1


# ---------------------------------------------------------------------------
# sync_obsidian_to_db — priority update
# ---------------------------------------------------------------------------


def test_sync_updates_priority_when_item_moves_sections(conn: sqlite3.Connection) -> None:
    """If an item exists in DB with different priority than its file section, update priority."""
    # Insert "Book flight Boston to Miami" as low priority (7) but it's in Urgent section (P1-P3)
    row_id = insert_action_item(
        conn, text="Book flight Boston to Miami", source="telegram", source_message_id=None, priority=7
    )
    item_before = get_item_by_id(conn, row_id)
    assert item_before.priority == 7

    sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)

    item_after = get_item_by_id(conn, row_id)
    assert item_after.priority <= PRIORITY_URGENT_MAX, (
        f"Priority should have been updated to urgent range, got {item_after.priority}"
    )
    # Verify priority actually changed
    assert item_after.priority != 7


def test_sync_does_not_change_priority_when_item_already_in_same_band(conn: sqlite3.Connection) -> None:
    """If an item is already in the same priority band as its file section, leave it alone."""
    # Insert "Learn Rust" with priority 8 (someday band = P7–P9)
    row_id = insert_action_item(
        conn, text="Learn Rust", source="telegram", source_message_id=None, priority=8
    )

    sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)

    item_after = get_item_by_id(conn, row_id)
    assert item_after.priority == 8


# ---------------------------------------------------------------------------
# sync_obsidian_to_db — idempotency
# ---------------------------------------------------------------------------


def test_sync_is_idempotent(conn: sqlite3.Connection) -> None:
    """Running sync twice must produce the same DB state as running it once."""
    result1 = sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)
    result2 = sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)

    # No new inserts on second run — all items already in DB
    assert result2.inserted_count == 0

    # Total row count must be the same after both runs
    cur = conn.execute("SELECT COUNT(*) FROM action_items")
    count = cur.fetchone()[0]
    assert count == result1.inserted_count + result1.done_count


def test_sync_idempotent_done_status(conn: sqlite3.Connection) -> None:
    """Running sync twice does not create duplicate done transitions."""
    row_id = insert_action_item(conn, text="Call the dentist", source="telegram", source_message_id=None)

    sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)
    first_done_at = get_item_by_id(conn, row_id).done_at

    sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)
    second_done_at = get_item_by_id(conn, row_id).done_at

    # done_at should not be overwritten on second pass (item is already done)
    assert first_done_at == second_done_at


# ---------------------------------------------------------------------------
# sync_obsidian_to_db — SyncResult summary
# ---------------------------------------------------------------------------


def test_sync_result_summary_counts_are_accurate(conn: sqlite3.Connection) -> None:
    """SyncResult must accurately report done/inserted/priority_changed counts."""
    # Pre-insert one item at wrong priority so priority_changed fires
    # "Book flight Boston to Miami" is in Urgent section (P1-P3), inserting at priority=8
    row_id = insert_action_item(
        conn, text="Book flight Boston to Miami", source="telegram", source_message_id=None, priority=8
    )
    # Pre-insert "Call the dentist" as open — it appears [x] in file, so should be marked done
    row_dentist = insert_action_item(conn, text="Call the dentist", source="telegram", source_message_id=None)

    result = sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)

    # "Call the dentist" was open → should be marked done (1 transition)
    assert result.done_count == 1
    assert get_item_by_id(conn, row_dentist).status == ActionItemStatus.DONE
    # "Complete FC work items", "Time box Lobster stuff", "Learn Rust" are new open items not in DB
    assert result.inserted_count == 3
    # "Book flight" was at wrong priority band (8 vs urgent max 3)
    assert result.priority_changed_count == 1


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------


def test_parse_handles_empty_file() -> None:
    """parse_active_todos on an empty string must return empty lists, not raise."""
    result = parse_active_todos("")
    assert result.open == []
    assert result.done == []


def test_parse_handles_file_with_no_checkboxes() -> None:
    """parse_active_todos on a file with no checkbox lines returns empty lists."""
    content = "# Some file\n\nNo checkboxes here.\n"
    result = parse_active_todos(content)
    assert result.open == []
    assert result.done == []


def test_parse_strips_inline_workstream_annotation() -> None:
    """Item text must not include the trailing *(workstream)* annotation."""
    content = "## Active (P4–P6)\n\n### lobster\n- [ ] Connect Obsidian to Lobster  *(lobster)*\n"
    result = parse_active_todos(content)
    assert len(result.open) == 1
    assert result.open[0].text == "Connect Obsidian to Lobster"
    assert "*(lobster)*" not in result.open[0].text


def test_sync_handles_empty_db_gracefully(conn: sqlite3.Connection) -> None:
    """sync_obsidian_to_db with an empty DB must not raise."""
    result = sync_obsidian_to_db(conn, SAMPLE_ACTIVE_TODOS)
    assert result is not None


# ---------------------------------------------------------------------------
# render_active_todos — format verification
# ---------------------------------------------------------------------------


def test_render_produces_urgent_section(conn: sqlite3.Connection) -> None:
    """render_active_todos must include the 'Urgent / This Week' section header."""
    insert_action_item(conn, text="Urgent task", source="telegram", source_message_id=None, priority=2)
    output = render_active_todos(conn)
    assert "Urgent / This Week" in output


def test_render_produces_someday_section(conn: sqlite3.Connection) -> None:
    """render_active_todos must include the 'Someday / Aspirational' section header."""
    insert_action_item(conn, text="Someday task", source="telegram", source_message_id=None, priority=8)
    output = render_active_todos(conn)
    assert "Someday / Aspirational" in output


def test_render_includes_open_items_as_checkboxes(conn: sqlite3.Connection) -> None:
    """render_active_todos must render open items as '- [ ] ...' checkboxes."""
    insert_action_item(conn, text="Buy milk", source="telegram", source_message_id=None)
    output = render_active_todos(conn)
    assert "- [ ] Buy milk" in output


def test_render_excludes_done_items_from_open_sections(conn: sqlite3.Connection) -> None:
    """Done items must not appear in the open (Urgent/Active/Someday) sections.

    render_active_todos intentionally includes recently-completed items in a
    trailing '<!-- done since last reset -->' block so users can see what they
    finished today.  The critical invariant is that done items do NOT appear as
    open checkboxes in the main body — only in the trailing done section.
    """
    row_id = insert_action_item(conn, text="Done task", source="telegram", source_message_id=None)
    mark_done(conn, row_id)
    output = render_active_todos(conn)

    # Split on the first '---' separator — everything before it is the open
    # items body; everything after may include the done-since-last-reset block.
    open_body, _sep, done_section = output.partition("\n---\n")

    assert "Done task" not in open_body, (
        "Done item must not appear in the open items sections (Urgent/Active/Someday)"
    )
    # Complementary: recently-done item appears in the trailing section.
    assert "Done task" in done_section, (
        "Recently-done item must appear in the trailing '<!-- done since last reset -->' block"
    )


def test_render_has_generation_header(conn: sqlite3.Connection) -> None:
    """render_active_todos must include the '# ✅ ACTIVE TODOS' title."""
    output = render_active_todos(conn)
    assert "# ✅ ACTIVE TODOS" in output


def test_render_excludes_future_snoozed_items(conn: sqlite3.Connection) -> None:
    """Items snoozed until a future date must be absent from render output.

    This test is the regression guard for the SQL defect where the WHERE clause
    tautologically included all snoozed rows regardless of snoozed_until.
    """
    row_id = insert_action_item(conn, text="Snoozed future task", source="telegram", source_message_id=None)
    # Snooze until a date far in the future — this item should be hidden
    mark_snoozed(conn, row_id, "2099-12-31")

    output = render_active_todos(conn)
    assert "Snoozed future task" not in output, (
        "Future-snoozed item must not appear in render output — snooze is not working"
    )


def test_render_includes_past_snoozed_items(conn: sqlite3.Connection) -> None:
    """Items whose snooze period has expired (snoozed_until in the past) must appear in render output."""
    row_id = insert_action_item(conn, text="Expired snooze task", source="telegram", source_message_id=None)
    # Snooze until a date already in the past — item should resurface
    mark_snoozed(conn, row_id, "2000-01-01")

    output = render_active_todos(conn)
    assert "Expired snooze task" in output, (
        "Past-expired snoozed item must appear in render output — snooze expiry is not working"
    )


# ---------------------------------------------------------------------------
# format_attribution — pure function, all four source types
# ---------------------------------------------------------------------------

# Spec: "2026-05-11T22:37:00Z" (UTC) → PDT (UTC-7 in May) → 3:37 PM PDT on Mon May 11
_SAMPLE_UTC_ISO = "2026-05-11T22:37:00Z"
# January date → PST (UTC-8)
_SAMPLE_UTC_ISO_PST = "2026-01-15T18:12:00Z"


def test_attribution_telegram_produces_archaeology_anchor() -> None:
    """source='telegram' must produce '[telegram msg · Mon May 11 · 3:37 PM PDT]'."""
    result = format_attribution("telegram", None, None, _SAMPLE_UTC_ISO)
    assert result == "[telegram msg · Mon May 11 · 3:37 PM PDT]"


def test_attribution_voice_produces_voicenote_anchor() -> None:
    """source='voice' must produce '[voicenote · Mon May 11 · 3:37 PM PDT]'."""
    result = format_attribution("voice", None, None, _SAMPLE_UTC_ISO)
    assert result == "[voicenote · Mon May 11 · 3:37 PM PDT]"


def test_attribution_direct_produces_direct_anchor() -> None:
    """source='direct' must produce '[direct · Mon May 11 · 3:37 PM PDT]'."""
    result = format_attribution("direct", None, None, _SAMPLE_UTC_ISO)
    assert result == "[direct · Mon May 11 · 3:37 PM PDT]"


def test_attribution_uses_pst_in_winter() -> None:
    """Timezone label must be PST (not PDT) when DST is not active."""
    # January 15, 2026 18:12 UTC → 10:12 AM PST
    result = format_attribution("telegram", None, None, _SAMPLE_UTC_ISO_PST)
    assert result is not None
    assert "PST" in result
    assert "PDT" not in result


def test_attribution_uses_pdt_in_summer() -> None:
    """Timezone label must be PDT when DST is active (May)."""
    result = format_attribution("telegram", None, None, _SAMPLE_UTC_ISO)
    assert result is not None
    assert "PDT" in result
    assert "PST" not in result


def test_attribution_obsidian_with_source_ref_produces_wiki_link() -> None:
    """source='obsidian' with source_ref must produce '[[doc-name]]'."""
    result = format_attribution("obsidian", "meetings/meeting-tania-2026-05-10.md", None, None)
    assert result == "[[meetings/meeting-tania-2026-05-10]]"


def test_attribution_obsidian_with_source_ref_and_section() -> None:
    """source='obsidian' with source_ref and source_section must produce '[[doc#section]]'."""
    result = format_attribution("obsidian", "meeting-tania-2026-05-10.md", "Next steps", None)
    assert result == "[[meeting-tania-2026-05-10#Next steps]]"


def test_attribution_obsidian_without_source_ref_returns_none() -> None:
    """source='obsidian' without source_ref must return None — no doc to link."""
    result = format_attribution("obsidian", None, None, None)
    assert result is None


def test_attribution_obsidian_source_constant_without_ref_returns_none() -> None:
    """source='obsidian:ACTIVE TODOS.md' (the legacy OBSIDIAN_SOURCE constant) without
    source_ref must return None — there is no meaningful link target."""
    result = format_attribution(OBSIDIAN_SOURCE, None, None, None)
    assert result is None


def test_attribution_missing_created_at_returns_label_only_for_non_obsidian() -> None:
    """If created_at is None for telegram/voice/direct, return the label-only form.

    When no timestamp is available the function cannot render a date or time,
    so it falls back to '[<label>]' rather than returning None. This preserves
    attribution provenance (the source medium) without fabricating a timestamp.
    """
    assert format_attribution("telegram", None, None, None) == "[telegram msg]"
    assert format_attribution("voice", None, None, None) == "[voicenote]"
    assert format_attribution("direct", None, None, None) == "[direct]"


def test_attribution_unknown_source_returns_none() -> None:
    """Unknown source values must return None (skip attribution)."""
    result = format_attribution("unknown_source", None, None, _SAMPLE_UTC_ISO)
    assert result is None


def test_attribution_empty_source_returns_none() -> None:
    """Empty source string must return None."""
    result = format_attribution("", None, None, _SAMPLE_UTC_ISO)
    assert result is None


# ---------------------------------------------------------------------------
# _render_attribution_line — indented sub-bullet
# ---------------------------------------------------------------------------


def test_render_attribution_line_uses_2space_indent() -> None:
    """Attribution sub-bullet must be indented with exactly 2 spaces."""
    line = _render_attribution_line("[telegram msg · Mon May 11 · 3:37 PM PDT]")
    assert line.startswith("  - ")


def test_render_attribution_line_matches_attribution_re() -> None:
    """Attribution line output must match ATTRIBUTION_LINE_RE for idempotency detection."""
    tg_line = _render_attribution_line("[telegram msg · Mon May 11 · 3:37 PM PDT]")
    voice_line = _render_attribution_line("[voicenote · Mon May 11 · 9:45 AM PDT]")
    direct_line = _render_attribution_line("[direct · Mon May 11 · 9:12 AM PDT]")
    wiki_line = _render_attribution_line("[[meeting-tania-2026-05-10#Next steps]]")
    assert ATTRIBUTION_LINE_RE.match(tg_line), f"telegram line did not match: {tg_line!r}"
    assert ATTRIBUTION_LINE_RE.match(voice_line), f"voice line did not match: {voice_line!r}"
    assert ATTRIBUTION_LINE_RE.match(direct_line), f"direct line did not match: {direct_line!r}"
    assert ATTRIBUTION_LINE_RE.match(wiki_line), f"wiki-link line did not match: {wiki_line!r}"


# ---------------------------------------------------------------------------
# render_active_todos — attribution sub-bullets in rendered output
# ---------------------------------------------------------------------------


def test_render_includes_attribution_for_telegram_item(conn: sqlite3.Connection) -> None:
    """render_active_todos must append an attribution sub-bullet for a telegram-sourced item."""
    # Insert with a known UTC timestamp
    conn.execute(
        """
        INSERT INTO action_items
            (text, source, source_message_id, extracted_at, priority, status, mention_count, dedup_key)
        VALUES (?, 'telegram', NULL, ?, 5, 'open', 1, ?)
        """,
        (
            "Follow up on law hosting decision",
            "2026-05-11T22:37:00+00:00",
            compute_dedup_key("Follow up on law hosting decision"),
        ),
    )
    conn.commit()

    output = render_active_todos(conn)

    assert "- [ ] Follow up on law hosting decision" in output
    assert "  - [telegram msg · Mon May 11 · 3:37 PM PDT]" in output


def test_render_includes_attribution_for_voice_item(conn: sqlite3.Connection) -> None:
    """render_active_todos must append a voicenote attribution sub-bullet."""
    conn.execute(
        """
        INSERT INTO action_items
            (text, source, source_message_id, extracted_at, priority, status, mention_count, dedup_key)
        VALUES (?, 'voice', NULL, ?, 8, 'open', 1, ?)
        """,
        (
            "Think through vault-watcher Tier 2",
            "2026-05-10T16:45:00+00:00",
            compute_dedup_key("Think through vault-watcher Tier 2"),
        ),
    )
    conn.commit()

    output = render_active_todos(conn)

    assert "  - [voicenote ·" in output


def test_render_includes_attribution_for_direct_item(conn: sqlite3.Connection) -> None:
    """render_active_todos must append a direct attribution sub-bullet."""
    conn.execute(
        """
        INSERT INTO action_items
            (text, source, source_message_id, extracted_at, priority, status, mention_count, dedup_key)
        VALUES (?, 'direct', NULL, ?, 5, 'open', 1, ?)
        """,
        (
            "Review this doc",
            "2026-05-11T16:12:00+00:00",
            compute_dedup_key("Review this doc"),
        ),
    )
    conn.commit()

    output = render_active_todos(conn)

    assert "  - [direct ·" in output


def test_render_omits_attribution_for_obsidian_item_without_source_ref(conn: sqlite3.Connection) -> None:
    """Items sourced from obsidian without a source_ref must not get an attribution sub-bullet."""
    # Legacy obsidian-sourced items (source = 'obsidian:ACTIVE TODOS.md') have no source_ref
    conn.execute(
        """
        INSERT INTO action_items
            (text, source, source_message_id, extracted_at, priority, status, mention_count, dedup_key)
        VALUES (?, ?, NULL, ?, 5, 'open', 1, ?)
        """,
        (
            "Plan the Tania ads campaign",
            OBSIDIAN_SOURCE,
            "2026-05-10T14:00:00+00:00",
            compute_dedup_key("Plan the Tania ads campaign"),
        ),
    )
    conn.commit()

    output = render_active_todos(conn)

    # The item itself must be present
    assert "Plan the Tania ads campaign" in output
    # But no attribution sub-bullet should follow it — no source_ref to link
    lines = output.splitlines()
    item_idx = next(
        (i for i, line in enumerate(lines) if "Plan the Tania ads campaign" in line), None
    )
    assert item_idx is not None
    # The line after the item (if it exists) must not be an attribution sub-bullet
    if item_idx + 1 < len(lines):
        next_line = lines[item_idx + 1]
        assert not ATTRIBUTION_LINE_RE.match(next_line), (
            f"Unexpected attribution sub-bullet after obsidian item: {next_line!r}"
        )


def test_render_attribution_appears_before_subtasks(conn: sqlite3.Connection) -> None:
    """Attribution sub-bullet must appear directly after the item line, before any subtasks."""
    # Insert parent item with telegram source
    parent_id = conn.execute(
        """
        INSERT INTO action_items
            (text, source, source_message_id, extracted_at, priority, status, mention_count, dedup_key)
        VALUES (?, 'telegram', NULL, ?, 5, 'open', 1, ?)
        """,
        (
            "Parent item with subtask",
            "2026-05-11T22:37:00+00:00",
            compute_dedup_key("Parent item with subtask"),
        ),
    ).lastrowid
    conn.commit()

    # Insert subtask
    insert_action_item(
        conn, text="Sub item under parent", source="telegram", source_message_id=None,
        parent_id=parent_id,
    )

    output = render_active_todos(conn)
    lines = output.splitlines()

    # Find the parent item line
    parent_idx = next(
        (i for i, line in enumerate(lines) if "Parent item with subtask" in line and "  " not in line[:3]),
        None,
    )
    assert parent_idx is not None, "Parent item not found in output"

    # The line immediately after the parent must be the attribution sub-bullet
    assert parent_idx + 1 < len(lines), "No lines after parent item"
    attr_line = lines[parent_idx + 1]
    assert ATTRIBUTION_LINE_RE.match(attr_line), (
        f"Expected attribution sub-bullet at line {parent_idx + 1}, got: {attr_line!r}"
    )

    # Subtask must follow the attribution line
    assert parent_idx + 2 < len(lines), "No lines after attribution"
    subtask_line = lines[parent_idx + 2]
    assert "Sub item under parent" in subtask_line


def test_render_subtasks_do_not_get_attribution(conn: sqlite3.Connection) -> None:
    """Subtasks (items with parent_id) must not receive their own attribution sub-bullet."""
    parent_id = conn.execute(
        """
        INSERT INTO action_items
            (text, source, source_message_id, extracted_at, priority, status, mention_count, dedup_key)
        VALUES (?, 'telegram', NULL, ?, 5, 'open', 1, ?)
        """,
        (
            "Top-level item",
            "2026-05-11T22:37:00+00:00",
            compute_dedup_key("Top-level item"),
        ),
    ).lastrowid
    conn.commit()

    insert_action_item(
        conn, text="Subtask item", source="telegram", source_message_id=None,
        parent_id=parent_id,
    )

    output = render_active_todos(conn)
    lines = output.splitlines()

    # Find the subtask line (2-space indent)
    subtask_idx = next(
        (i for i, line in enumerate(lines) if "Subtask item" in line), None
    )
    assert subtask_idx is not None

    # The subtask line itself starts with "  - [ ]" — that's the subtask, not an attribution
    # The line AFTER the subtask must not be an attribution sub-bullet for the subtask
    if subtask_idx + 1 < len(lines):
        next_line = lines[subtask_idx + 1]
        # An attribution line would also start with "  - " but would match ATTRIBUTION_LINE_RE
        # A subtask's content is not its own item, so no attribution should follow
        assert not (
            ATTRIBUTION_LINE_RE.match(next_line) and "Subtask item" not in next_line
        ), f"Unexpected attribution after subtask: {next_line!r}"


# ---------------------------------------------------------------------------
# apply_status_delta — checkbox flip behavior
# Named constants matching the spec requirements (prevents magic literals)
# ---------------------------------------------------------------------------

# How many empty polls trigger cooldown — not applicable here, but the naming
# convention carries: every spec-derived threshold gets a constant.
DISABLE_PROCESSING_GUARD = "- [ ] DISABLE PROCESSING"
DISABLE_PROCESSING_GUARD_EMOJI = "- [ ] 🔒 DISABLE PROCESSING"


def _make_conn(tmp_path: Path) -> sqlite3.Connection:
    """Create a fresh in-memory-equivalent DB in tmp_path for a single test."""
    return connect(tmp_path / "delta_test.db")


# ---------------------------------------------------------------------------
# Test 1: DB says done, file shows [ ] → file gets flipped to [x]
# ---------------------------------------------------------------------------

def test_apply_delta_flips_open_to_done_when_db_says_done(tmp_path: Path) -> None:
    """DB status=done + file shows '- [ ] ...' → output contains '- [x] ...'."""
    db = _make_conn(tmp_path)
    row_id = insert_action_item(db, text="Review the contract", source="telegram", source_message_id=None)
    mark_done(db, row_id)

    file_content = "## Active (P4–P6)\n- [ ] Review the contract\n"

    result = apply_status_delta(file_content, db)

    assert "- [x] Review the contract" in result
    assert "- [ ] Review the contract" not in result
    db.close()


# ---------------------------------------------------------------------------
# Test 2: DB says open, file shows [x] → file gets flipped back to [ ]
# ---------------------------------------------------------------------------

def test_apply_delta_flips_done_to_open_when_db_says_open(tmp_path: Path) -> None:
    """DB status=open + file shows '- [x] ...' → output contains '- [ ] ...'."""
    db = _make_conn(tmp_path)
    insert_action_item(db, text="Write the report", source="telegram", source_message_id=None)
    # DB status is 'open' (default) — file shows it as checked

    file_content = "## Active (P4–P6)\n- [x] Write the report\n"

    result = apply_status_delta(file_content, db)

    assert "- [ ] Write the report" in result
    assert "- [x] Write the report" not in result
    db.close()


# ---------------------------------------------------------------------------
# Test 3: DB says snoozed (not done), file shows [x] → flip back to [ ]
# ---------------------------------------------------------------------------

def test_apply_delta_flips_done_to_open_when_db_says_snoozed(tmp_path: Path) -> None:
    """DB status=snoozed (not done) + file shows '[x]' → flip back to '[ ]'.

    Snoozed items are not done; they are temporarily hidden. If the file shows
    them as checked while the DB has them snoozed, the function must restore the
    open checkbox to match the DB's 'not done' intent.
    """
    db = _make_conn(tmp_path)
    row_id = insert_action_item(db, text="Plan the roadmap", source="telegram", source_message_id=None)
    mark_snoozed(db, row_id, "2099-12-31")  # snoozed far in the future → status='snoozed'

    # Verify the DB has it snoozed (not done)
    item = get_item_by_id(db, row_id)
    assert item.status == ActionItemStatus.SNOOZED

    file_content = "## Active (P4–P6)\n- [x] Plan the roadmap\n"

    result = apply_status_delta(file_content, db)

    # Snoozed = not done → file's [x] must be flipped back to [ ]
    assert "- [ ] Plan the roadmap" in result
    assert "- [x] Plan the roadmap" not in result
    db.close()


# ---------------------------------------------------------------------------
# Test 4: Item in DB not in file → appended in lobster-additions block
# ---------------------------------------------------------------------------

def test_apply_delta_appends_db_only_item_in_additions_block(tmp_path: Path) -> None:
    """Open item in DB that does not appear in file is appended in <!-- lobster-additions --> block."""
    db = _make_conn(tmp_path)
    # Item in DB that is NOT in the file
    insert_action_item(db, text="Send weekly update", source="telegram", source_message_id=None)

    # File has a different item so file_dedup_keys is non-empty
    file_content = "## Active (P4–P6)\n- [ ] Unrelated task already in file\n"

    result = apply_status_delta(file_content, db)

    assert _LOBSTER_ADDITIONS_MARKER in result
    assert "Send weekly update" in result
    assert _LOBSTER_ADDITIONS_END in result
    db.close()


# ---------------------------------------------------------------------------
# Test 5: Existing additions block is replaced (not duplicated) on second run
# ---------------------------------------------------------------------------

def test_apply_delta_replaces_additions_block_not_duplicated(tmp_path: Path) -> None:
    """Running apply_status_delta twice produces exactly one additions block, not two."""
    db = _make_conn(tmp_path)
    insert_action_item(db, text="Follow up with Alice", source="telegram", source_message_id=None)

    # File has an unrelated item so the DB item needs to be appended
    file_content = "## Active (P4–P6)\n- [ ] Anchor item in file\n"

    # First run — produces additions block
    result_first = apply_status_delta(file_content, db)
    assert result_first.count(_LOBSTER_ADDITIONS_MARKER) == 1

    # Second run — must not duplicate the block
    result_second = apply_status_delta(result_first, db)
    assert result_second.count(_LOBSTER_ADDITIONS_MARKER) == 1, (
        "Additions block was duplicated on second run"
    )
    assert result_second.count(_LOBSTER_ADDITIONS_END) == 1
    db.close()


# ---------------------------------------------------------------------------
# Test 6: DISABLE PROCESSING guard line is never touched
# ---------------------------------------------------------------------------

def test_apply_delta_never_modifies_disable_processing_guard(tmp_path: Path) -> None:
    """The '- [ ] DISABLE PROCESSING' guard line must pass through unchanged even if the
    DB happens to have a dedup_key that matches.

    The guard line is exempt from checkbox flipping by spec — vault-processor.py
    uses its unchecked state as a sentinel to proceed.
    """
    db = _make_conn(tmp_path)
    # Insert a DB item whose text is exactly "DISABLE PROCESSING" — the function
    # must skip it regardless due to the explicit guard check in the implementation.
    insert_action_item(db, text="DISABLE PROCESSING", source="direct", source_message_id=None)
    mark_done(db, 1)  # DB says done

    file_content = "- [ ] 🔒 DISABLE PROCESSING\n- [ ] Normal task\n"
    # Also insert a DB item for "Normal task" to confirm other items are still processed
    insert_action_item(db, text="Normal task", source="telegram", source_message_id=None)
    mark_done(db, 2)

    result = apply_status_delta(file_content, db)

    lines = result.splitlines()
    # The guard line must remain '- [ ]' (unchecked)
    guard_lines = [l for l in lines if "DISABLE PROCESSING" in l]
    assert guard_lines, "DISABLE PROCESSING guard line disappeared"
    for guard_line in guard_lines:
        assert "- [ ]" in guard_line, (
            f"DISABLE PROCESSING guard was modified: {guard_line!r}"
        )
    db.close()


# ---------------------------------------------------------------------------
# Test 7: Subtask items (parent_id IS NOT NULL) are excluded from additions block
# ---------------------------------------------------------------------------

def test_apply_delta_excludes_subtasks_from_additions_block(tmp_path: Path) -> None:
    """Items with parent_id IS NOT NULL must not appear in the additions block.

    Only top-level items (parent_id IS NULL) are appended — subtasks belong
    structurally under their parent and should never be floated to the top level.
    """
    db = _make_conn(tmp_path)
    parent_id = insert_action_item(
        db, text="Parent action item", source="telegram", source_message_id=None
    )
    # Subtask — has parent_id set
    insert_action_item(
        db, text="Subtask under parent", source="telegram", source_message_id=None,
        parent_id=parent_id,
    )

    # File has an anchor item so the additions block will be generated
    # Neither the parent nor subtask appears in the file
    file_content = "## Active (P4–P6)\n- [ ] Anchor item already in file\n"

    result = apply_status_delta(file_content, db)

    assert _LOBSTER_ADDITIONS_MARKER in result, "Expected additions block to be present"
    # Parent should appear (parent_id IS NULL)
    assert "Parent action item" in result
    # Subtask must NOT appear in the additions block
    assert "Subtask under parent" not in result, (
        "Subtask with parent_id should not appear in lobster-additions block"
    )
    db.close()


# ---------------------------------------------------------------------------
# Test 8: Attribution line is appended alongside item in additions block
#          when source_ref is present (or source is telegram with timestamp)
# ---------------------------------------------------------------------------

def test_apply_delta_appends_attribution_in_additions_block(tmp_path: Path) -> None:
    """Items appended to the additions block must include an attribution sub-bullet
    when source type supports attribution (telegram with timestamp).

    The attribution sub-bullet appears immediately after the item's checkbox line
    inside the additions block, matching the format produced by format_attribution().
    """
    db = _make_conn(tmp_path)
    # Insert with explicit extracted_at so format_attribution produces a full timestamp
    db.execute(
        """
        INSERT INTO action_items
            (text, source, source_message_id, extracted_at, priority, status, mention_count, dedup_key)
        VALUES (?, 'telegram', NULL, ?, 5, 'open', 1, ?)
        """,
        (
            "Schedule dentist appointment",
            "2026-05-11T22:37:00+00:00",
            compute_dedup_key("Schedule dentist appointment"),
        ),
    )
    db.commit()

    # File has anchor item; the telegram item needs to be appended
    file_content = "## Active (P4–P6)\n- [ ] Anchor item in file\n"

    result = apply_status_delta(file_content, db)

    assert "Schedule dentist appointment" in result
    # Attribution sub-bullet must appear in the block — format is "[telegram msg · ...]"
    assert "[telegram msg ·" in result, (
        "Expected telegram attribution sub-bullet in additions block"
    )
    db.close()


# ---------------------------------------------------------------------------
# Test 9: Idempotency — running apply_status_delta twice produces same result
# ---------------------------------------------------------------------------

def test_apply_delta_is_idempotent(tmp_path: Path) -> None:
    """Running apply_status_delta twice on the same file+DB state produces identical output.

    This is the core contract: the function must not accumulate changes across
    repeated calls. The second call sees the same DB state and must produce the
    same string as the first.
    """
    db = _make_conn(tmp_path)
    # Mix of scenarios: DB-done item shown open, DB-open item shown done, and
    # an item in DB but absent from file
    done_id = insert_action_item(db, text="Finished task", source="telegram", source_message_id=None)
    mark_done(db, done_id)

    open_id = insert_action_item(db, text="Open task", source="telegram", source_message_id=None)

    insert_action_item(db, text="Telegram only task", source="telegram", source_message_id=None)

    file_content = (
        "## Active (P4–P6)\n"
        "- [ ] Finished task\n"    # DB=done, file=open → will be flipped to [x]
        "- [x] Open task\n"        # DB=open, file=done → will be flipped to [ ]
    )

    result_first = apply_status_delta(file_content, db)
    result_second = apply_status_delta(result_first, db)

    assert result_first == result_second, (
        "apply_status_delta is not idempotent: second call produced different output"
    )
    db.close()
