#!/bin/bash
#===============================================================================
# Lobster Container Init — runs once at systemd boot as a oneshot service
#
# Responsibilities:
#   1. Write config.env from environment variables injected by docker-compose.
#      The docker-compose env_file (config.staging.env) sets TELEGRAM_BOT_TOKEN,
#      LOBSTER_ENV, etc. — this script materialises them into the file that the
#      lobster systemd services load via EnvironmentFile=.
#
#   2. Run install.sh --container-setup for runtime setup:
#      - Verifies sqlite-vec loads correctly
#      - Creates CLAUDE.md and .claude/ symlinks in $WORKSPACE_DIR
#      - Creates stub user-config agent files
#      - Seeds canonical memory templates (idempotent)
#
#   3. Update ~/.claude/settings.json MCP registration to point at the inbox
#      server running in this container (the host settings.json path is correct,
#      but this is idempotent and ensures it's always current).
#
# This script runs as the lobster user (see lobster-container-init.service).
# It must complete before lobster-router/lobster-claude/lobster-mcp-local start.
#===============================================================================

set -euo pipefail

LOBSTER_DIR="/home/lobster/lobster"
WORKSPACE_DIR="/home/lobster/lobster-workspace"
MESSAGES_DIR="/home/lobster/messages"
CONFIG_DIR="/home/lobster/lobster-config"
LOG_DIR="$WORKSPACE_DIR/logs"

export PATH="/home/lobster/.local/bin:/usr/local/bin:/usr/bin:/bin"

echo "[container-init] Starting..."

#-------------------------------------------------------------------------------
# 1. Write config.env from environment variables
#
# docker-compose env_file injects TELEGRAM_BOT_TOKEN, LOBSTER_ENV, etc. into
# the container environment. The lobster systemd services load config.env via
# EnvironmentFile=, so we materialise the runtime values here.
#
# LOBSTER_ENV must be "production" — the dispatcher exits immediately if it is
# not. The staging config.staging.env.example documents this requirement.
#-------------------------------------------------------------------------------
mkdir -p "$CONFIG_DIR"
LOG_FILE="$LOG_DIR/container-init.log"
mkdir -p "$LOG_DIR"

# Only write config.env if it doesn't already exist (volume persistence across restarts)
if [ ! -f "$CONFIG_DIR/config.env" ]; then
    echo "[container-init] Writing config.env from environment..."
    cat > "$CONFIG_DIR/config.env" << CONFIG
# Lobster Staging Config — generated by lobster-container-init.sh
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS:-}
LOBSTER_ADMIN_CHAT_ID=${LOBSTER_ADMIN_CHAT_ID:-${TELEGRAM_ALLOWED_USERS:-}}
LOBSTER_ENV=${LOBSTER_ENV:-production}
LOBSTER_DEBUG=${LOBSTER_DEBUG:-false}
CONFIG
    echo "[container-init] config.env written."
else
    echo "[container-init] config.env already exists (volume restart) — skipping write."
fi

#-------------------------------------------------------------------------------
# 2. Run install.sh --container-setup
#
# Idempotent — safe to run on every boot. Handles:
#   - sqlite-vec load verification
#   - CLAUDE.md and .claude/ symlinks
#   - Stub user-config agent files
#   - Canonical memory template seeding
#   - lobster-state.json seeding with booted_at
#-------------------------------------------------------------------------------
echo "[container-init] Running install.sh --container-setup..."
LOBSTER_INSTALL_DIR="$LOBSTER_DIR" \
LOBSTER_WORKSPACE="$WORKSPACE_DIR" \
LOBSTER_MESSAGES="$MESSAGES_DIR" \
LOBSTER_CONFIG_DIR="$CONFIG_DIR" \
    bash "$LOBSTER_DIR/install.sh" --container-setup 2>&1 | tee -a "$LOG_FILE" || true
echo "[container-init] Container setup complete."

#-------------------------------------------------------------------------------
# 3. Update Claude settings.json MCP registration
#
# The ~/.claude dir is bind-mounted from the host. The host settings.json
# already has the correct lobster-inbox HTTP registration (http://localhost:8766/mcp),
# which is identical inside the container — no change needed here.
#
# This step is kept as a safety net in case the mounted settings.json is missing
# the registration (e.g. fresh Claude Code install on the host).
#-------------------------------------------------------------------------------
SETTINGS_FILE="/home/lobster/.claude/settings.json"
if [ -f "$SETTINGS_FILE" ]; then
    if ! python3 -c "import json; d=json.load(open('$SETTINGS_FILE')); exit(0 if 'lobster-inbox' in str(d) else 1)" 2>/dev/null; then
        echo "[container-init] MCP registration not found in settings.json — registering..."
        /home/lobster/.local/bin/claude mcp add --transport http lobster-inbox \
            -s user http://localhost:8766/mcp 2>/dev/null || true
    else
        echo "[container-init] MCP registration present — skipping."
    fi
fi

echo "[container-init] Done."
