-- Migration 0028: document wos-metrics.db schema.
--
-- wos-metrics.db is a separate SQLite DB (not registry.db) that records
-- prescription and closure events for structural analysis.
-- Schema is created lazily by PrescriptionMetricsLogger._ensure_schema().
-- This file documents the intended schema for reference; it is not applied
-- by the migrate.py runner (which operates on registry.db only).
--
-- Tables: prescription_events, closure_events
-- See src/orchestration/prescription_metrics.py for field definitions.
--
-- prescription_events:
--   id                         INTEGER PRIMARY KEY AUTOINCREMENT
--   recorded_at                TEXT NOT NULL  -- ISO-8601 UTC
--   uow_id                     TEXT NOT NULL
--   cycle                      INTEGER NOT NULL
--   executor_type              TEXT
--   has_minimum_viable_output  INTEGER        -- 0/1
--   has_boundary               INTEGER        -- 0/1
--   has_success_criteria_check INTEGER        -- 0/1
--   estimated_cycles           INTEGER
--   word_count                 INTEGER
--   step_count                 INTEGER
--   source_issue               TEXT
--
-- closure_events:
--   id                         INTEGER PRIMARY KEY AUTOINCREMENT
--   recorded_at                TEXT NOT NULL
--   uow_id                     TEXT NOT NULL
--   total_cycles               INTEGER NOT NULL
--   closure_outcome            TEXT NOT NULL
--   final_prescription_cycle   INTEGER
